<a href="https://colab.research.google.com/github/Jinwoo-Kwak/AI-Camp/blob/main/2022%20AI%20Camp/Additional_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = a.flat[3]
print(b)

4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Additional excercise

###Create a 2d array, sort the array by a given row

In [ ]:
X = np.random.randint(10,23)
# your code goes here
np.sort(X)

AxisError: ignored

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Delete a particular row from an array

In [ ]:
# your code goes here
np.delete(X,2,axis=0)

array([[13, 11, 21, 10],
       [16, 19, 13, 15]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 5 by 5 matrix and print the values 1,2,3,4 just below the diagnol

In [ ]:
'''

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

'''
# your code goes here
np.diagflat([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

