<a href="https://colab.research.google.com/github/bestgradient/AI-Camp-Summer-2022/blob/main/ML_Activtity/Scratch_Nerual_nets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
#Neural network model (forward propagation)
'''
Input layer -> L hidden layer -> output layer(last layer)
'''

Example:
Input layer:5
1 hidden layer: 3
output layer(last layer): 1

In [25]:
X = np.random.randn(5,3) * 0.01 # input data

In [14]:
W1 = np.random.randn(3,5) * 0.01 # correct shape for dot product
b1 = np.zeros((1,1))
W2 = np.random.randn(1,3) * 0.01 # correct shape for dot product. last A1(activation output) = (a,b), current A2 = (c,a)
b2 = np.zeros((1,1))

In [17]:
print(W1)
print(b1)
print(W2)
print(b2)

[[ 0.00432933 -0.00308959  0.01356833  0.00438554  0.00501488]
 [ 0.00034423 -0.00803444  0.02600598  0.01833496 -0.01460826]
 [-0.00273848 -0.00819981  0.00619279 -0.0057288   0.00254499]]
[[0.]]
[[ 0.01391593 -0.01968056  0.00401513]]
[[0.]]


In [18]:
def sigmoid(z):
  
    g = 1/(1+np.exp(-z))
   
    return g

In [37]:
def relu(Z):
  return np.maximum(0,Z)

In [20]:
def forward_propagation(X, W1,b1,W2,b2):
    
    
    Z1 = np.dot(W1,X) + b1 # input for activation function
    A1 = relu(Z1) # activation of hidden layer
    Z2 = np.dot(W2,A1) + b2 # input for activation function
    A2 = sigmoid(Z2) # activation of last layer
    
    return A2 # output of last activation function

In [40]:
forward_propagation(X,W1,b1,W2,b2)

array([[0.49999923, 0.5       , 0.49999894]])