In [ ]:
#Contd. Numpy
#   - copy
#   - boolean arrays
#   - Matrix operations
#   - vectors operations

#python
#   - class, class variables, class functions in python

In [ ]:
# https://docs.python.org/3/library/copy.html
import numpy as np

a = np.random.randint(10,23,size=(4,4))

print("A = ", a)
b = a
print("B = ", b)
b[0][0] = -12121

print("after A = ", a)
print("after B = ", b)


#
c = a.copy()
print("C = ", c)
c[0][0] = -21
print("after C = ", c)
print("Second after A = ", a)

In [ ]:


B = np.array([True, False, True, False])
print(B)

B == False

a = np.arange(10)
print(a)

a >= 5

a[a >= 5 ] = -1
print(a)

a[a < a.mean()] = -1
print(a)


a[(a == -1) | (a==2)] = 0
print(a)

In [ ]:
a = np.random.randint(10,23,size=(4,4))
b =  np.random.randint(10,23,size=(4,3))


print(a)
print(b)

print(a + b)
print(a - b)




In [ ]:
x = np.random.randint(10,23,size=(2,2))
y =  np.random.randint(10,23,size=(2,2))

print(x)
print(y)

print(x * y)


print(x.T)
print(y.T)

In [ ]:
x = np.random.randint(10,83,size=(2,2))
y =  np.random.randint(10,23,size=(2,2))

#commutative  x * y == y * x   no
print(x * y)
print(y * x)

print(x.dot(y))

#aasociative x * ( y * z) = (x * y) *z  no

[[ 924 1168]
 [ 380  392]]
[[ 924 1168]
 [ 380  392]]
[[2311 1694]
 [ 972  712]]


In [ ]:
x = np.random.randint(10,83,size=(2,3))
y =  np.random.randint(10,23,size=(3,2))

#Please go through numpy docs, google it and explain each of these functions

# print(x * y)
# print(y * x) 
# Above operations does the elementwise multiplication

#Below 3 operatiosn are the actual matrix multiplication [high school math]
print(x.dot(y))
print(y.dot(x))

print(x @ y)
print(y @ x)

print(np.matmul(x, y))
print(np.matmul(y, x))


In [ ]:
#Vector
#Notes and HW excercise

Python class and objects

In [ ]:
class cal():

  def __init__(self,a,b):
    self.a=a
    self.b=b

  def addition(self):
    return self.a+self.b

  def subtraction(self):
    return self.a-self.b

  def division (self):
    return self.a/self.b  

  def multiplication (self):
    return self.a*self.b    

In [ ]:
a = int(input("give me a: "))
b = int(input("give me b: "))

give me a: 2
give me b: 4


In [ ]:
initialising_class = cal(a,b)


In [ ]:
initialising_class.subtraction()

6

In [ ]:
initialising_class.addition()

6

In [ ]:
initialising_class.division()

0.5

In [ ]:
initialising_class.multiplication()

8

In [ ]:
def additionnnnn(a,b):
  return a+b

In [ ]:
additionnnnn(2,4)

6