In [ ]:
'''

numpy
  - function
  - operations
  - examples (hands-on)

Why use?
  - structure
  - easy to access
  - manage data

Data
 - any facts
EX: email spam, face detection. hand written digit recognition, ...


Read data from multiples sources - csv, excel, datbase, internet....


what is Data Analysis?
  - Data analysis is a process of inspecting, cleansing, transforming, and 
  modelling data with the goal of discovering useful information, informing 
  conclusions, and supporting decision-making.


Tools data analysis
 - excel
 - R
 - tableau
 - python
 

 Why python?
  - simple, intuitive and readable
  - many libraries
  - free and open source


Real example of using numpy, pandas, matplotlib 
  - jupyter notebook

'''
'''
- Intro to Numpy
  Reference: 
  https://www.w3schools.com/python/numpy/numpy_intro.asp#:~:text=NumPy%20is%20a%20Python%20library,you%20can%20use%20it%20freely.
  https://numpy.org/

https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods
https://numpy.org/doc/stable/user/quickstart.html
https://www.w3schools.com/python/numpy/numpy_array_slicing.asp

  
- Intro Pandas

- Examples and more examples'''




In [ ]:
import numpy as ny

In [ ]:
lt = [1, 2, 3, 4]
rt = ny.array([1, 2, 3, 4])

print("My list :" , lt)
print("Numpy list :" , rt)

My list : [1, 2, 3, 4]
Numpy list : [1 2 3 4]


In [ ]:
print(lt[1])
print(rt[1])

2
2


In [ ]:
a = ny.array([0, 1.5, 1, 3])


In [ ]:
a[0], a[1]

a[:]

a[1:]

a[:-1]

a[1:3]

array([1.5, 1. ])

In [ ]:
# array[start: end: step_size]
# [0, 1.5, 1, 3]
a[::2]
# 0, 1

b = ny.array([0.5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
b[::20]
print(b[::2])
print(b[::20])

[ 0.5  3.   5.   7.   9.  11.  13. ]
[0.5]


In [ ]:
b[::-1]  # numpy array - prints array in the reverse order

array([13. , 12. , 11. , 10. ,  9. ,  8. ,  7. ,  6. ,  5. ,  4. ,  3. ,
        2. ,  0.5])

In [ ]:
lt  #list
lt[::-1]
lt[::2]

[1, 3]

In [ ]:
print(b)
# b[::]
b[3: 10:-1] # 10, 8 , 6 , 4

print(b[3::-1]) #[4.  3.  2.  0.5]
print(b[:10:-1]) #[13. 12.]

print(b[3: 10: -1]) #[]
print(b[3: 10: -2]) #[]

print(b[10:3]) #[]
print(b[10: 3: -1]) #[11. 10.  9.  8.  7.  6.  5.]


[ 0.5  2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13. ]
[4.  3.  2.  0.5]
[13. 12.]
[]
[]
[]
[11. 10.  9.  8.  7.  6.  5.]
[11.  9.  7.  5.]


In [ ]:
print(b)
print(b[3: 10:-2])  #[11.  9.  7.  5.]

[ 0.5  2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13. ]
[]


In [ ]:
b[3:10:-2]

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.empty(4)

array([0., 0., 0., 0.])

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import random
np.random.rand() 

array([[[0.04793816, 0.83206077, 0.06781212, 0.94158005, 0.15483021],
        [0.98462146, 0.51630602, 0.27609693, 0.18961107, 0.4913672 ],
        [0.26467347, 0.70035469, 0.46838193, 0.07868866, 0.5704138 ],
        [0.77206904, 0.3783626 , 0.89619553, 0.90273073, 0.85324394]],

       [[0.92125846, 0.74968452, 0.55576025, 0.03369325, 0.76387543],
        [0.36009438, 0.56007591, 0.51422315, 0.14408403, 0.72279142],
        [0.39846506, 0.34871696, 0.02308236, 0.88607801, 0.97150769],
        [0.1486794 , 0.6657853 , 0.9065189 , 0.85136363, 0.68242732]],

       [[0.64389591, 0.9301077 , 0.2778477 , 0.86460305, 0.33359655],
        [0.90342033, 0.67016866, 0.61802436, 0.07403272, 0.6983284 ],
        [0.86888161, 0.61724576, 0.02920063, 0.35274406, 0.00534783],
        [0.32420046, 0.78510513, 0.68035891, 0.32109073, 0.20314383]]])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11])

# Error  ValueError: cannot reshape array of size 11 into shape (6,2)
#a.reshape(6, 2) 


In [ ]:
a.max()

11

In [ ]:
np.random.randint(10,23,size=(3,4))

array([[19, 10, 19, 10],
       [18, 19, 20, 22],
       [12, 13, 18, 18]])

In [ ]:
b

range(0, 15)

In [ ]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
c = np.array([1,2,3,4,5,623523,7,8,9,10,11])


In [ ]:
np.concatenate((a,b,c))

array([     1,      2,      3,      4,      5,      6,      7,      8,
            9,     10,     11,      1,      2,      3,      4,      5,
            6,      7,      8,      9,     10,     11,      1,      2,
            3,      4,      5, 623523,      7,      8,      9,     10,
           11])

In [ ]:
a=[1,2,3,4,5]
b= [4,5,6,7,78]

In [ ]:
k=a.append(b)

In [ ]:
a[-1]

[4, 5, 6, 7, 78]

In [ ]:
a.extend(b)

In [ ]:
a

[1, 2, 3, 4, 5, 4, 5, 6, 7, 78]

In [ ]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
a = np.array([1,2,3,4,5,6,7,8,9,10,11])


11

In [ ]:
a.size

11

In [ ]:
arr = np.array([1,2,3,544,52424,5567656,7,8,9])

In [ ]:
arr.shape

(9,)

In [ ]:
arr.size

9

In [ ]:
arr.sum()

45

In [ ]:
arr.std()

2.581988897471611

In [ ]:
a.var()

10.0

In [ ]:
arr.mean()

5.0

In [ ]:
arr.sort()

In [ ]:
arr.squeeze()

array([      1,       2,       3,       7,       8,       9,     544,
         52424, 5567656])

###More numpy functions on 2D arrays

In [ ]:
# Create a 2d array of randomNumber of size (4,4)

#netra #Minerva
np.random.randint(1,100,size=(4,4))
np.random.randint(1,90,size=(4,4))


#Yash #Ayush
np.random.rand(4,4)
np.random.rand(4,4)

#Walker
np.random.rand(16).reshape((4, 4))

#Shriram
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a.reshape(4,4)


np.random.randint(5, size=(4,4))



array([[3, 1, 0, 0],
       [1, 0, 0, 0],
       [3, 3, 1, 0],
       [2, 1, 4, 2]])

In [ ]:
np.random.rand(4,4,3)

In [ ]:
np.zeros((5, 5))
x = np.ones((5, 5))

x.size
x.shape

np.random.rand(4,4,4)

In [ ]:
#concatenate
# create 2 2D array with random number and try concatenate
'''
1 2
3 4
5 6
7 8

'''


a = np.random.rand(2,2)
b = np.random.rand(2,2)

print(a.shape, b.shape)
c = np.concatenate((a, b))
c.shape

'''
1 2        6 7              
3 4        8 9


1 2 6 7
3 4 8 9
'''
d = np.concatenate((a, b), axis=1)
print(d, d.shape)

Submit Answer »


(2, 2) (2, 2)
[[0.03537192 0.47994656 0.94487873 0.73607313]
 [0.75120598 0.23093717 0.15950998 0.88375543]] (2, 4)


In [ ]:
x = np.random.randint(1, 26, size=(5,5))
print(x)
print(x[0][2])
print(x[0,2])

x[:,:]
x[0, :]
x[:, 3]

#x[:, 4] = 0

x[1:3, 2:3] = -1

print(x[1, :] <= 10)
print(x[:, -1] >=10)

x[x[:, -1] >=10] = 2000
print(x)


[[21 19 16 24 18]
 [ 3 22 18 15 14]
 [ 1 23 16 21 19]
 [22 17  1 19 11]
 [ 7  9  3 22  2]]
16
16
[ True False  True False False]
[ True  True  True  True False]


In [ ]:
np.ones((5,5))
np.zeros((5,5))

'''
identity matrix
  - square matrix : same no of rows and columns
  - only diagonal elements are one
  - rest of the elements are zero

Ex: 1 0 
    0 1

    1 0 0
    0 1 0
    0 0 1

'''

np.identity(5)


In [ ]:
#explore
x = ny.random.randint(1, 26, size=(5,5))
print(x)

x[x[:, -2] >=10] = 2000
print(x)

[[22 24 17 24  4]
 [21 12 20  6 23]
 [15 10 22  6  5]
 [22  2  2 24 12]
 [ 1  3  6  4  4]]
[[2000 2000 2000 2000 2000]
 [  21   12   20    6   23]
 [  15   10   22    6    5]
 [2000 2000 2000 2000 2000]
 [   1    3    6    4    4]]


In [ ]:
#mean
#sum
#std
#var
x = np.random.randint(1, 26, size=(5,5))
print(x)
print(x.sum()) #sum all elements in the array
print(x.mean())

print(x.sum(axis=0))  #sum along the rows
print(x.sum(axis=1)) #sum along the colmns

print(x.mean(axis=0))  #sum along the rows
print(x.mean(axis=1)) #sum along the colmns

print(x.std(axis=0))  #sum along the rows
print(x.std(axis=1)) #sum along the colmns


[[ 6 17 17  3 14]
 [19 23  9 12 17]
 [21  7 24  1  6]
 [12 14 17  6  2]
 [ 7  6 12 12  1]]
285
11.4
[65 67 79 34 40]
[57 80 59 51 38]
[13.  13.4 15.8  6.8  8. ]
[11.4 16.  11.8 10.2  7.6]
[6.09918027 6.34350061 5.11468474 4.53431362 6.41872261]
[5.81721583 4.97995984 9.01997783 5.45527268 4.12795349]
