<a href="https://colab.research.google.com/github/conuwoo/AI-Camp-Summer-2022/blob/main/ML_Activity/Scratch_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
#download perceptron.data file

In [85]:
import numpy as np
import pandas as pd

def readDataFile(fileName):
  return pd.read_csv(fileName, names=['x1','x2','x3','x4','y'])

In [86]:
from sklearn.model_selection import train_test_split

def splitData(data, t_size):
  return train_test_split(data,test_size=t_size, random_state=42)


In [87]:
def get_X_Y(data):
  return data.loc[:,'x1':'x4'].values, data.loc[:,'y'].values

In [88]:
'''
x = [x1 x2 x3 x4]
w = [w1 w2 w3 w4]
b = c

Ex: for single column_or_1d
  x = [a]
  w = [b]
  b = c

  w*b = ab
  y = w * x + b //simple mathematical operation

For multiple columns of x, where no of columns > 1
  x = [x1 x2 x3 x4]
  w = [w1 w2 w3 w4]
  b = c

  x and w are vectors
    x * w = (x1.w1 + x2.w2 + x3.w3 + x4.w4)

  Since x  and w are represent as row matrix(if any doubt, google about 'row matrix)
  we have to take xT * w       <- only change betweeen single feature and multiple feature
'''

#For multiple columns of x, where no of columns > 1

# h(x)
def _hypo(X,w,b):
  #return w*X.T + b
  return np.dot(X,w) +b

# loss(x)
def _loss_Simplified(X,Y,w,b):
  # max{0,-y(X*w.T + b)}
  loss = (-Y * _hypo(X,w,b))
  loss[loss >= 0] = 1
  loss[loss < 0] = 0
  return loss
#gradient descent()
''' initial w,b
    w(t+1) = w(t) - stepSize * delta_w(t)
    b(t+1) = b(t) - stepSize * delta_b(t)

    until min is found or loss == 0
'''
def gradientDescent(X,Y,w0,b0,stepSize): 
  #initial w0,b0
  w_t = w0
  b_t = b0
  it = 1

  loss = _loss_Simplified(X,Y,w_t,b_t)
  no_of_misc = sum(loss)
  while(no_of_misc != 0):
    delta_w, delta_b = 0,0
    #do the gradient descent
    for i in range(X.shape[0]):
        delta_w += Y[i] * X[i] * loss[i]
        delta_b += Y[i] * loss[i]

    w_t1 = w_t + stepSize * delta_w
    b_t1 = b_t + stepSize * delta_b

    loss = _loss_Simplified(X,Y,w_t1,b_t1)
    no_of_misc = sum(loss)

    w_t = w_t1
    b_t = b_t1
    it +=1
  return w_t, b_t, it

In [89]:
data = readDataFile('perceptron.data')
tr_data, tst_data = splitData(data,0.05)

X,Y = get_X_Y(tr_data)

w,b,it = gradientDescent(X,Y,[1,1,1,1],1,0.1)

print(w)
print(b)

print("No of iteration: ",it)

Xt,Yt = get_X_Y(tst_data)
ls = _loss_Simplified(Xt,Yt,w,b)
print("Accuracy :", 1-(sum(ls)/ls.shape[0]))

[ 44.40535358  16.03440064   0.58879373 -51.36453489]
-96.50000000000009
No of iteration:  115
Accuracy : 1.0


In [90]:
w,b,it = gradientDescent(X,Y,[0,0,0,0],0,0.1)

print(w)
print(b)

print("No of iteration: ", it)
Xt,Yt = get_X_Y(tst_data)
ls = _loss_Simplified(Xt,Yt,w,b)
print("Accuracy :", 1-(sum(ls)/ls.shape[0]))

[ 64.81324808  23.24820627   1.05333214 -75.33225399]
-140.70000000000002
No of iteration:  40
Accuracy : 1.0


In [91]:
w,b,it = gradientDescent(X,Y,[0,0,0,0],0,1)

print(w)
print(b)

print("No of iteration: ", it)
Xt,Yt = get_X_Y(tst_data)
ls = _loss_Simplified(Xt,Yt,w,b)
print("Accuracy :", 1-(sum(ls)/ls.shape[0]))

[ 648.13248083  232.48206272   10.53332143 -753.32253989]
-1407.0
No of iteration:  40
Accuracy : 1.0
